eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9102
spring:
  application:
    name: mservice
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      ssl-auto: true